USE [Temporario]
GO

/****** Object:  Table [dbo].[Acesso]    Script Date: 15/01/2020 10:18:55 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Acesso](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Login] [nchar](100) NOT NULL,
	[Senha] [nchar](1000) NOT NULL,
 CONSTRAINT [PK_Acesso] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


